# Generated by Django 5.2.4 on 2025-08-15 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagesegment',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='recommended_products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.recommendationlog'),
        ),
        migrations.AddField(
            model_name='styleembedding',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='styleembedding',
            name='segment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.imagesegment'),
        ),
        migrations.AddField(
            model_name='styleimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='style_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.styleimage'),
        ),
        migrations.AddField(
            model_name='imagesegment',
            name='style_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='recommendations.styleimage'),
        ),
    ]
