# Generated by Django 5.2.4 on 2025-08-23 10:35

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleembedding',
            name='embeddings',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=2048, null=True),
        ),
    ]
